-- setie el name de artworks para que sea MAYUSCUla todo
-- puse la Fk de comentarios Artworks_id con ON DELETE = SET NULL para que se puedan borrar los productos
-- hice lo de created_at y updated_at